# Generated by Django 4.0.5 on 2022-06-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10000)),
                ('Country', models.CharField(max_length=10000)),
                ('State', models.CharField(max_length=10000)),
                ('City', models.CharField(max_length=10000)),
                ('House_address', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10000)),
                ('Biograpghy', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=10000)),
                ('Hospital_name', models.CharField(max_length=10000)),
                ('Hospital_address', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Product_price', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=6)),
                ('Age', models.IntegerField()),
                ('Biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.bio')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.address')),
                ('Medical', models.ManyToManyField(to='records.doctor')),
            ],
        ),
    ]
